---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gke-goglides-ingress
  annotations:
    # kubernetes.io/ingress.global-static-ip-name: gke-goglides-static-ip
    networking.gke.io/managed-certificates: gke-test-cluster-certificate
spec:
  backend:
    serviceName: hello-world-service
    servicePort: 80